name: Workflow Evento
on:
  push:
jobs:
  apenas-main:
    name: Esse job sรณ executa na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main"