name: Workflow Concorrencia
run-name: Workflow Concorrencia ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      chave:
        type: string
        default: pipeline-aula
jobs:
  exemplo-fluxo-execucao-01:
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.chave }}
    steps:
      - name: Execução do job teste
        run: |
          sleep 120;
          echo "Action executada job 01"

  exemplo-fluxo-execucao-02:
    runs-on: ubuntu-latest
    needs: [exemplo-fluxo-execucao-01]
    steps:
      - name: Execução do job teste
        run: |
          sleep 120;
          echo "Action executada job 02"

