name: Workflow Evento
on:
  push:
jobs:
  exemplo-fluxo-execucao-01:
    runs-on: ubuntu-latest
    steps:
      - name: Vai falhar
        run: 1
  exemplo-fluxo-execucao-02:
    runs-on: ubuntu-latest
    steps:
      - name: Execução com sucesso
        run: echo "Execução de Fluxo"