name: Workflow Evento
on:
  pull_request:
    branches: ["main"]
    types: closed
jobs:
  teste:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: echo "Action executadas apenas em features"
        
      - name: Alteração no card
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Adicionando comentário aqui sobre PR'
            })
