name: Workflow Evento
on:
  push:
    branches: ["main", "feature/*"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: echo "Action executadas apenas em main e features"
